In [13]:
import pandas as pd
import requests
import json

In [5]:
ocak = pd.read_csv("ocak.csv")
subat = pd.read_csv("şubat.csv")
mart = pd.read_csv("mart.csv")
nisan = pd.read_csv("nisan.csv")
mayis = pd.read_csv("mayıs.csv")
haziran = pd.read_csv("haziran.csv")
temmuz = pd.read_csv("temmuz.csv")
agustos = pd.read_csv("agustos.csv")
eylul = pd.read_csv("eylül.csv")
ekim = pd.read_csv("ekim.csv")
kasim = pd.read_csv("kasım.csv")
aralik = pd.read_csv("aralık.csv")

df = pd.concat([ocak, subat, mart, nisan, mayis, haziran, temmuz, agustos, eylul, ekim, kasim, aralik], ignore_index=True)

In [6]:
df.shape

(19080773, 8)

In [7]:
df.head()

,DATE_TIME,LATITUDE,LONGITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
0,2024-01-01 00:00:00,41.338806,27.965698,sx7ghm,31,121,76,9
1,2024-01-01 00:00:00,41.157532,29.174194,sxkdpu,69,89,81,2
2,2024-01-01 00:00:00,41.058655,28.361206,sxk1t6,22,145,80,23
3,2024-01-01 00:00:00,40.954285,29.086304,sxk8vz,1,75,30,45
4,2024-01-01 00:00:00,41.003723,28.855591,sxk928,4,37,20,29

In [8]:
df.tail()

,DATE_TIME,LATITUDE,LONGITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
19080768,2024-12-31 23:00:00,40.943298,29.295044,sxkbft,14,71,42,39
19080769,2024-12-31 23:00:00,40.959778,29.207153,sxkc08,11,69,44,6
19080770,2024-12-31 23:00:00,41.174011,28.877563,sxkd1p,30,134,86,176
19080771,2024-12-31 23:00:00,41.168518,29.174194,sxkdpy,52,89,67,4
19080772,2024-12-31 23:00:00,41.195984,28.866577,sxkd2g,65,144,89,182

In [9]:
df.describe()

,LATITUDE,LONGITUDE,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
count,1.908077e+07,1.908077e+07,1.908077e+07,1.908077e+07,1.908077e+07,1.908077e+07
mean,4.106297e+01,2.888705e+01,2.289682e+01,1.018081e+02,5.653555e+01,1.082300e+02
std,1.009562e-01,3.565224e-01,2.432780e+01,3.688158e+01,2.590732e+01,1.392274e+02
min,4.076752e+01,2.796570e+01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,4.099823e+01,2.869080e+01,3.000000e+00,7.200000e+01,3.300000e+01,2.000000e+01
50%,4.105865e+01,2.893250e+01,1.000000e+01,1.010000e+02,5.400000e+01,5.800000e+01
75%,4.113007e+01,2.915222e+01,4.200000e+01,1.300000e+02,8.000000e+01,1.390000e+02
max,4.134430e+01,2.963562e+01,2.100000e+02,2.550000e+02,2.100000e+02,2.056000e+03

In [10]:
df.to_csv("trafik.csv", index=False)

In [16]:
import requests
import pandas as pd

# API URL'si
url = "https://archive-api.open-meteo.com/v1/archive"

# Parametreler (İstanbul koordinatları)
params = {
    "latitude": 41.0082,
    "longitude": 28.9784,
    "start_date": "2024-01-01",
    "end_date": "2024-12-31",
    "hourly": [
        "temperature_2m",
        "precipitation",
        "windspeed_10m",
        "relative_humidity_2m",
        "cloudcover"
    ],
    "timezone": "Europe/Istanbul"
}

# API isteği gönder
response = requests.get(url, params=params)
data = response.json()

# JSON'u pandas DataFrame'e dönüştür
hava_df = pd.DataFrame({
    "Tarih_Saat": data["hourly"]["time"],
    "Sicaklik": data["hourly"]["temperature_2m"],
    "Yagis": data["hourly"]["precipitation"],
    "Ruzgar_Hizi": data["hourly"]["windspeed_10m"],
    "Nem": data["hourly"]["relative_humidity_2m"],
    "Bulutluluk": data["hourly"]["cloudcover"]
})

# CSV'ye kaydet
hava_df.to_csv("istanbul_hava_durumu_saatlik_2024.csv", index=False)

hava_df.head()

         Tarih_Saat  Sicaklik  Yagis  Ruzgar_Hizi  Nem  Bulutluluk
0  2024-01-01T00:00       7.6    0.0          9.0   93          40
1  2024-01-01T01:00       8.8    0.0          7.4   87          91
2  2024-01-01T02:00       9.8    0.0          9.2   83          98
3  2024-01-01T03:00       9.9    0.0          9.2   82         100
4  2024-01-01T04:00       8.7    0.0          6.1   90          97